#!/bin/bash

: ${LOGFILE:=/tmp/plugn_download.log}
: ${DEBUG:=1}

main(){
  url=$(echo $PAYLOAD | cut -d" " -f 1);
  dest=$(echo $PAYLOAD | cut -d" " -f 2);
  debug "url=$url dest=$dest"
  curl -Lko $dest $url
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"