#!/bin/bash

: ${LOGFILE:=/tmp/plugn_download.log}
: ${DEBUG:=1}

main(){
  echo $PAYLOAD | read url dest
  debug "url=$url dest=$dest"
  curl -Lko $dest $url
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"