#!/bin/bash

: ${LOGFILE:=/var/log/consul-watch/consul_handler.log}

main(){
  yum -y install postgresql-server postgresql-contrib
  if service postgresql status > /dev/null; then
    service postgresql stop
  fi

  export ROOT_PW=admin
  export PGDATA=/var/lib/pgsql/data


  echo "$ROOT_PW" >> /tmp/pw
  rm -rf $PGDATA
  su postgres -c 'initdb -U postgres --pwfile=/tmp/pw --auth=md5'
  rm -f /tmp/pw
  systemctl enable postgresql
  systemctl start postgresql
}

exec &>> "$LOGFILE"
[[ "$0" == "$BASH_SOURCE" ]] && main "$@"

